name: tests ⚙️

on: [ push, pull_request ]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: Setup Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: anaconda, conda-forge


    - name: Install requirements 📦
      run: |
        conda install eccodes
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install -r requirements-dev.txt
        python3 setup.py install
        mkdir -p /opt/csv2bufr
        cd /opt/csv2bufr
        wget https://github.com/wmo-im/csv2bufr-templates/archive/refs/tags/v0.1.tar.gz
        tar -zxf v0.1.tar.gz --strip-components=1 csv2bufr-templates-0.1/templates
        export BUFR_ORIGINATING_CENTRE 0
        export BUFR_ORIGINATING_SUBCENTRE 0
    - name: run tests ⚙️
      run: |
        pytest
    - name: run flake8 ⚙️
      run: |
        flake8
